### ISSUE TITLE
Лишние запуски CI

### ISSUE THREAD

**Issue by geogreck** [bmstu-iu9/ptp2022-8-todo-list#4]
Это дублирование issue 16 из старого репозитория.

К сожалению, не могу это сделать самостоятельно, так как весь CI завязан на make файлах

Код для получения измененных файлов, используемый мною, прилагаю:

```yml
            - name: Get file changes
              id: get_file_changes
              uses: trilom/file-changes-action@v1.2.4
              with:
                  output: ' '

            - name: Echo file changes
              id: hello
              run: |
                  echo Added files: ${{ steps.get_file_changes.outputs.files_added }}
                  echo Changed files: ${{ steps.get_file_changes.outputs.files_modified }}
                  echo Removed files: ${{ steps.get_file_changes.outputs.files_removed }}

```

**Comment by stewkk** [comment]
> Код для получения измененных файлов, используемый мною, прилагаю:
> 
> ```yaml
>             - name: Get file changes
>               id: get_file_changes
>               uses: trilom/file-changes-action@v1.2.4
>               with:
>                   output: ' '
> 
>             - name: Echo file changes
>               id: hello
>               run: |
>                   echo Added files: ${{ steps.get_file_changes.outputs.files_added }}
>                   echo Changed files: ${{ steps.get_file_changes.outputs.files_modified }}
>                   echo Removed files: ${{ steps.get_file_changes.outputs.files_removed }}
> ```

Такой код все равно запускает CI, который работает 13 секунд:
![image](https://user-images.githubusercontent.com/43303621/177977663-78161ae3-5184-4a10-bac9-edb3b5c38885.png)

Предлагаю запускать CI в PR только при наличии изменений в соответствующих файлах, а при мердже в main ветку - всегда. 

Достичь этого можно следующим кодом:
```yaml
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - "**.go"
      - "go.**"
```
[Ссылка на документацию](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore)
